name: 'Determine Version'
description: 'Determines and sets the package version based on event context'
inputs:
  event_name:
    description: 'The name of the triggering event (e.g., push, release)'
    required: true
  github_ref:
    description: 'The GitHub ref that triggered the workflow (for extracting tag version)'
    required: true
  language:
    description: 'The programming language package to update (python or r)'
    required: true
    default: 'python'
outputs:
  version:
    description: 'The determined version'
    value: ${{ steps.set-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: pip install tomli
      shell: bash
    - name: Determine and set version
      id: set-version
      shell: bash
      run: |
        if [ "${{ inputs.event_name }}" == "release" ]; then
          # Extract version from tag (removing 'v' prefix if present)
          TAG_VERSION="${{ inputs.github_ref }}"
          TAG_VERSION=${TAG_VERSION#refs/tags/}
          VERSION=${TAG_VERSION#v}
          echo "Version from release tag: $VERSION"

          # Use the appropriate update script with the release version based on language
          # If the language is R, then just read the version from the DESCRIPTION file,
          # this should be updated by the release process manually
          if [ "${{ inputs.language }}" == "r" ]; then
            # Read the version from the DESCRIPTION file
            VERSION=$(grep -E '^Version:' r-phylo2vec/DESCRIPTION | awk '{print $2}')
            echo "Version from DESCRIPTION file: $VERSION"
          else
            python resources/update_python_version.py $VERSION
          fi
        else
          # Run the script without parameters to use timestamp versioning
          if [ "${{ inputs.language }}" == "r" ]; then
            python resources/update_r_version.py
          else
            python resources/update_python_version.py
          fi
        fi

        # Set the version as an output that can be used by other steps
        echo "version=$VERSION" >> $GITHUB_OUTPUT
